Class {
	#name : #TomeCSSClasses,
	#superclass : #SharedPool,
	#classVars : [
		'DEFINITION_BODY',
		'END_PAGE_SPACE',
		'FEATURE_CONTENT',
		'FEATURE_SCENARIO_SPLITTER',
		'SCENARIOS_FAILED',
		'SCENARIOS_PASSED',
		'SCENARIO_BODY_ERROR',
		'SCENARIO_BODY_FAILED',
		'SCENARIO_BODY_PASSED',
		'SCENARIO_CONTAINER',
		'SCENARIO_ERROR',
		'SCENARIO_HEADER',
		'SCENARIO_LABEL',
		'SCENARIO_SECTION_SPLITTER',
		'TEST_RESULT_SUMARY'
	],
	#category : #'Tome-Tools-WebApp'
}

{ #category : #'class initialization' }
TomeCSSClasses class >> initialize [ 

	"Not sure if I should keep css classes as constants"
]
