SystemOrganization addCategory: #'DomainValidationMagritte-Tests'!
SystemOrganization addCategory: #'DomainValidationMagritte-Tests-Extensions'!
SystemOrganization addCategory: #'DomainValidationMagritte-Tests-Instrument'!
SystemOrganization addCategory: #'DomainValidationMagritte-Tests-Link'!
SystemOrganization addCategory: #'DomainValidationMagritte-Tests-Manifest'!
SystemOrganization addCategory: #'DomainValidationMagritte-Tests-Validations'!
