name: Tome CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:11
    steps:
      - uses: actions/checkout@v2
      - name: Load Tome and Test it
        run: |
          ls -la
          pharo /opt/pharo/Pharo.image eval --save "Metacello new repository: 'tonel://pharo'; baseline: 'Tome'; load: #(dev)"
          pharo /opt/pharo/Pharo.image test Tome-Tests Tome-Examples --junit-xml-output --fail-on-failure --fail-on-error


