name: Tome CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:9
    steps:
      - uses: actions/checkout@v2
      - name: Load Tome and Test it
        run: |
          ls -la
          pharo /opt/pharo/Pharo.image eval --save "Metacello new repository: 'tonel://tome/pharo'; baseline: 'SBDD'; load: #(core tests)"
          pharo /opt/pharo/Pharo.image test SBDD-Tests --junit-xml-output --fail-on-failure --fail-on-error


