name: Tome CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:9
    steps:
      - uses: actions/checkout@v2
      - name: Load Tome and Test it
        run: |
          ls -la
          cd /
          ls -la __w/tome
          ./pharo /Pharo.image eval "Metacello new repository: 'tonel://__w/tome/pharo'; baseline: 'SBDD'; load: #(core tests)"


