name: Tome CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:11
    steps:
      - uses: actions/checkout@v2
      - name: Load Tome and Test it
        run: |
          pharo /opt/pharo/Pharo.image st --save --quit loadForTesting.st
          pharo /opt/pharo/Pharo.image test Tome-Tests --junit-xml-output --fail-on-failure --fail-on-error
          pharo /opt/pharo/Pharo.image featureRun Tome-Examples

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: specification-execution-result
          path: target/specificationTestResult/*


